package utils

import (
	"fmt"
	"strings"
)

// Shell identifies a supported shell dialect for `awsd init` / `awsd shellenv`.
type Shell string

const (
	Bash       Shell = "bash"
	Zsh        Shell = "zsh"
	Fish       Shell = "fish"
	PowerShell Shell = "powershell"
)

// SupportedShells is the canonical list, in help/doc order.
var SupportedShells = []string{"bash", "zsh", "fish", "powershell"}

// AcceptedShells is everything ParseShell takes, including aliases. Used for
// argument validation and completion.
var AcceptedShells = append(append([]string{}, SupportedShells...), "pwsh")

// ParseShell maps a user-supplied shell name to a Shell.
func ParseShell(name string) (Shell, error) {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "bash":
		return Bash, nil
	case "zsh":
		return Zsh, nil
	case "fish":
		return Fish, nil
	case "powershell", "pwsh":
		return PowerShell, nil
	}
	return "", fmt.Errorf("unsupported shell %q (supported: %s)", name, strings.Join(SupportedShells, ", "))
}

// quote wraps a value in single quotes, escaped for the given shell. Profile
// names come from ~/.aws/config and can contain spaces and quotes, so this has
// to hold up against anything that ends up in ~/.awsd.
func quote(sh Shell, value string) string {
	switch sh {
	case Fish:
		// Inside fish single quotes only \ and ' are special.
		r := strings.NewReplacer(`\`, `\\`, `'`, `\'`)
		return "'" + r.Replace(value) + "'"
	case PowerShell:
		// Inside PowerShell single quotes only ' is special, doubled to escape.
		return "'" + strings.ReplaceAll(value, "'", "''") + "'"
	default:
		// POSIX: end the quoted run, emit an escaped quote, reopen.
		return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
	}
}

func exportLine(sh Shell, name, value string) string {
	switch sh {
	case Fish:
		return fmt.Sprintf("set -gx %s %s", name, quote(sh, value))
	case PowerShell:
		return fmt.Sprintf("$env:%s = %s", name, quote(sh, value))
	default:
		return fmt.Sprintf("export %s=%s", name, quote(sh, value))
	}
}

func unsetLines(sh Shell, names ...string) []string {
	switch sh {
	case Fish:
		return []string{"set -e " + strings.Join(names, " ")}
	case PowerShell:
		lines := make([]string, 0, len(names))
		for _, n := range names {
			lines = append(lines, fmt.Sprintf("$env:%s = $null", n))
		}
		return lines
	default:
		return []string{"unset " + strings.Join(names, " ")}
	}
}

// ShellEnv renders the env mutations for a given state as shell code, ready to
// be eval'd by the function that `awsd init` generates. It is the single
// implementation of the ~/.awsd contract that the wrapper scripts used to
// duplicate per shell:
//
//   - empty profile        -> unset AWS_PROFILE (this is "default")
//   - no region= line      -> leave AWS_REGION/AWS_DEFAULT_REGION alone
//   - region= with no value -> unset both
func ShellEnv(s State, sh Shell) string {
	var lines []string

	if s.Profile == "" {
		lines = append(lines, unsetLines(sh, "AWS_PROFILE")...)
	} else {
		lines = append(lines, exportLine(sh, "AWS_PROFILE", s.Profile))
	}

	if s.RegionSet {
		if s.Region == "" {
			lines = append(lines, unsetLines(sh, "AWS_REGION", "AWS_DEFAULT_REGION")...)
		} else {
			lines = append(lines,
				exportLine(sh, "AWS_REGION", s.Region),
				exportLine(sh, "AWS_DEFAULT_REGION", s.Region),
			)
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

// InitScript returns the shell integration to be eval'd from a shell rc file.
// It defines the awsd function, wires up completion, and applies the state
// already in ~/.awsd so a new shell starts on the active profile.
func InitScript(sh Shell) string {
	switch sh {
	case Bash:
		return posixInit(Bash, "")
	case Zsh:
		return posixInit(Zsh, zshCompinit)
	case Fish:
		return fishInit
	case PowerShell:
		return powershellInit
	}
	return ""
}

// zsh needs bashcompinit to get the bash-style `complete` builtin, and
// bashcompinit needs compinit to have run first for compdef to exist. Most
// setups (oh-my-zsh and friends) have already run it, so only pay for it here
// if nothing else did.
const zshCompinit = `if (( ! $+functions[compdef] )); then
  autoload -Uz compinit && compinit
fi
autoload -U +X bashcompinit && bashcompinit
`

// posixInit covers bash and zsh, which differ only in needing bashcompinit to
// provide the bash-style `complete` builtin.
func posixInit(sh Shell, compinit string) string {
	return fmt.Sprintf(posixInitTemplate, string(sh), compinit)
}

const posixInitTemplate = `# awsd shell integration (%[1]s). Generated by: awsd init %[1]s
# Add to your rc file with: eval "$(awsd init %[1]s)"

awsd() {
  command awsd "$@" || return
  eval "$(command awsd shellenv %[1]s)"
}

_awsd_completion() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=${COMP_WORDS[COMP_CWORD-1]}
  local subcmd=${COMP_WORDS[1]}
  local suggestions

  case "$COMP_CWORD" in
    1)
      suggestions="$(command awsd list profiles) list set unset"
      ;;
    2)
      case "$subcmd" in
        set|unset) suggestions="profile region" ;;
        list|l)    suggestions="profiles regions" ;;
        *)         suggestions="" ;;
      esac
      ;;
    3)
      case "$subcmd $prev" in
        "set profile") suggestions="$(command awsd list profiles)" ;;
        "set region")  suggestions="$(command awsd list regions)" ;;
        *)             suggestions="" ;;
      esac
      ;;
    *)
      suggestions=""
      ;;
  esac

  COMPREPLY=($(compgen -W "$suggestions" -- "$cur"))
  return 0
}

%[2]scomplete -o nospace -F _awsd_completion awsd

# Apply the profile/region already in ~/.awsd to this shell.
eval "$(command awsd shellenv %[1]s)"
`

const fishInit = `# awsd shell integration (fish). Generated by: awsd init fish
# Add to ~/.config/fish/config.fish with: awsd init fish | source

function awsd
    command awsd $argv; or return
    command awsd shellenv fish | source
end

complete -c awsd -f
complete -c awsd -n __fish_use_subcommand -a '(command awsd list profiles)'
complete -c awsd -n __fish_use_subcommand -a 'list set unset'
complete -c awsd -n '__fish_seen_subcommand_from set unset' -a 'profile region'
complete -c awsd -n '__fish_seen_subcommand_from list l' -a 'profiles regions'
complete -c awsd -n '__fish_seen_subcommand_from profile' -a '(command awsd list profiles)'
complete -c awsd -n '__fish_seen_subcommand_from region' -a '(command awsd list regions)'

# Apply the profile/region already in ~/.awsd to this shell.
command awsd shellenv fish | source
`

const powershellInit = `# awsd shell integration (PowerShell). Generated by: awsd init powershell
# Add to your $PROFILE with: awsd init powershell | Out-String | Invoke-Expression

# Resolve the binary once, before the function below shadows the name. Unlike
# POSIX "command", PowerShell's & operator does not skip functions, so calling
# "& awsd" inside function awsd would recurse forever.
$global:AwsdBin = (Get-Command -CommandType Application awsd -ErrorAction SilentlyContinue |
    Select-Object -First 1).Source
if (-not $global:AwsdBin) {
    Write-Error "awsd: could not find the awsd binary on PATH"
    return
}

function awsd {
    param([Parameter(ValueFromRemainingArguments = $true)] [string[]] $Arguments)
    & $global:AwsdBin @Arguments
    if ($LASTEXITCODE -ne 0) { return }
    & $global:AwsdBin shellenv powershell | Out-String | Invoke-Expression
}

Register-ArgumentCompleter -CommandName awsd -ParameterName Arguments -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)

    $words = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() })
    if ($wordToComplete) { $words = @($words | Select-Object -SkipLast 1) }

    $suggestions = @()
    if ($words.Count -eq 0) {
        $suggestions = @(& $global:AwsdBin list profiles) + @('list', 'set', 'unset')
    } elseif ($words.Count -eq 1) {
        if ($words[0] -in @('set', 'unset')) { $suggestions = @('profile', 'region') }
        elseif ($words[0] -in @('list', 'l')) { $suggestions = @('profiles', 'regions') }
    } elseif ($words.Count -eq 2 -and $words[0] -eq 'set') {
        if ($words[1] -eq 'profile') { $suggestions = @(& $global:AwsdBin list profiles) }
        elseif ($words[1] -eq 'region') { $suggestions = @(& $global:AwsdBin list regions) }
    }

    $suggestions | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}

# Apply the profile/region already in ~/.awsd to this shell.
& $global:AwsdBin shellenv powershell | Out-String | Invoke-Expression
`
