#!/usr/bin/env bash

if [[ "$1" == "version" ]]; then
  _awsd_prompt version
  return
fi

# check if $1 is empty
if [ -z "$1" ]
then
  # no argument passed
  AWS_PROFILE="$AWS_PROFILE" _awsd_prompt
else
  # argument passed, assume it's a profile name
  AWS_PROFILE="$AWS_PROFILE" _awsd_prompt "$1"
fi

selected_profile="$(cat ~/.awsd)"

if [ -z "$selected_profile" ]
then
  unset AWS_PROFILE
else
  export AWS_PROFILE="$selected_profile"
fi
