name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7

    - name: Run tests with coverage
      run: |
        go test ./... -coverprofile=coverage.out
        go tool cover -func=coverage.out
